### ISSUE TITLE
Says 'Unknown Project'

### ISSUE THREAD

**Issue by mathiasm** [wakatime/sketch-wakatime#2]
Anyway to see the name of the projects/files we work on?

**Comment by alanhamlett** [comment]
One of these 4 ways are available:

https://wakatime.com/faq#set-project-name

**Comment by alecilea** [comment]
Hi all, I can't understand how to change the name project created automatically by the wakatime sketch plugin. Can you explain me step-by-step? I cannot find the wakatime config file.. or I don't understand the FAQ. Thanks!

**Comment by alanhamlett** [comment]
WakaTime tracks your Sketch usage based on the current file you are editing, so to prevent a file/project from being tracked you must exclude that file's path. To exclude a file path you create an exclusion rule in your `~/.wakatime.cfg` file (located in your home folder) that matches some part of the file's full path. For example, if you're editing a drawing saved to `/Users/me/Dropbox/my-project/drawing1.sketch` then your rule could match the project part of that file path like this:

```
[settings]
api_key = <api key>
exclude =
    /Dropbox/my-project/
```

That would prevent tracking any files inside your `Dropbox/my-project/` folder. Here are some more examples:
https://github.com/wakatime/wakatime#configuring

To rename a project, the easiest way is to create an empty file inside your project's folder named `.wakatime.project`. Then type the new project name as the first line of that file. For example, if you created a `.wakatime-project` file at `/Users/me/Dropbox/my-project/.wakatime-project` with the first line:
ProjectZ
Then all files you edit which are inside the my-project folder will be logged to a project named ProjectZ.

**Comment by LasseRafn** [comment]
How would I go about setting a .wakatime-project file for each of my Sketch files, in a way that would not have me waste an hour

**Comment by alanhamlett** [comment]
You shouldn't create a `.wakatime-project` for each Sketch file, only one for each project/client. The way you do that is use one folder per project/client and put all your Sketch files for that client into that project folder. Then you only need to create one `.wakatime-project` file per project/client.

Instead of using a `.wakatime-project` file you can also track your project/client folder using Git. When using Git, the top folder in Git is used as the project's name. The good thing about Git is you can use branches to designate tasks or work items, and then filter by them on the project's dashboard on wakatime.com.

**Comment by adejonghm** [comment]
Hi. I changed the name of a project without any problem, but now I have two projects with the same code. I don't want the oldest appears on my Dashboard anymore and I wish the newest shows the total coding activity. Is it possible to transfer my active coding from the oldest to the newest project?

Thanks!!

**Comment by alanhamlett** [comment]
You should rename the project from the website to have the same name as the new project, that way it's merged into the new project:
https://wakatime.com/faq#rename-projects
